### ISSUE TITLE
Missing babel-preset-stage-1 in dependencies.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/builder-docs-archetype#42]
https://www.npmjs.com/package/babel-preset-stage-1

```
[builder:run] webpack-static - webpack --config node_modules/builder-docs-archetype/config/webpack/webpack.config.static.js --progress --bail
 40% 1/2 build modulesModuleBuildError: Module build failed: Error: Couldn't find preset "stage-1" relative to directory "/Users/rye/scm/fmd/formidable-spectacle-docs/src/components"
    at OptionManager.mergePresets (/Users/rye/scm/fmd/formidable-spectacle-docs/node_modules/builder-docs-archetype/node_modules/babel-core/lib/transformation/file/options/option-manager.js:327:17)
    at OptionManager.mergeOptions (/Users/rye/scm/fmd/formidable-spectacle-docs/node_modules/builder-docs-archetype/node_modules/babel-core/lib/transformation/file/options/option-manager.js:287:12)
    at OptionManager.init (/Users/rye/scm/fmd/formidable-spectacle-docs/node_modules/builder-docs-archetype/node_modules/babel-core/lib/transformation/file/options/option-manager.js:416:10)
    at File.initOptions (/Users/rye/scm/fmd/formidable-spectacle-docs/node_modules/builder-docs-archetype/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/Users/rye/scm/fmd/formidable-spectacle-docs/node_modules/builder-docs-archetype/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/Users/rye/scm/fmd/formidable-spectacle-docs/node_modules/builder-docs-archetype/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transpile (/Users/rye/scm/fmd/formidable-spectacle-docs/node_modules/builder-docs-archetype/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/rye/scm/fmd/formidable-spectacle-docs/node_modules/builder-docs-archetype/node_modules/babel-loader/index.js:88:12)
    at NormalModule.onModuleBuildFailed (/Users/rye/scm/fmd/formidable-spectacle-docs/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/Users/rye/scm/fmd/formidable-spectacle-docs/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /Users/rye/scm/fmd/formidable-spectacle-docs/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/Users/rye/scm/fmd/formidable-spectacle-docs/node_modules/webpack-core/lib/NormalModuleMixin.js:173:4)
    at nextLoader (/Users/rye/scm/fmd/formidable-spectacle-docs/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /Users/rye/scm/fmd/formidable-spectacle-docs/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/rye/scm/fmd/formidable-spectacle-docs/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/rye/scm/fmd/formidable-spectacle-docs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

**Comment by ryan-roemer** [comment]
This appears to have been accidentally working before... 

As a bandaid in a `-docs` lander repo you can:

```sh
$ yarn add --dev babel-preset-stage-1
```
